Repository ssginc-be/Pickypal-WMS, pull requests merged in 2024-12, with the labels that each got.

#22 Gradle의 Java toolchain 버전 변경 (18-->17)
  api/build.gradle
Labels: bug, backend

#23 item 도메인 클래스에 대한 package refactoring
  api/src/main/java/com/pickypal/api/item/Emart24ItemCrawlController.java
  api/src/main/java/com/pickypal/api/item/Emart24ItemCrawlService.java
  api/src/main/java/com/pickypal/api/item/Item.java
  api/src/main/java/com/pickypal/api/item/ItemRepository.java
Labels: bug, backend

#29 상품(item) 엔티티 필드 수정
  api/src/main/java/com/pickypal/api/item/Emart24ItemCrawlService.java
  api/src/main/java/com/pickypal/api/item/Item.java
  api/src/main/java/com/pickypal/api/supplier/SupplierRepository.java
Labels: bug, crawling, batch, backend

#32 회원가입/로그인 API 구현
  api/build.gradle
  api/src/main/java/com/pickypal/api/auth/AuthController.java
  api/src/main/java/com/pickypal/api/auth/AuthService.java
  api/src/main/java/com/pickypal/api/auth/FirebaseLoginRequestDto.java
  api/src/main/java/com/pickypal/api/auth/FirebaseLoginResponseDto.java
  api/src/main/java/com/pickypal/api/auth/FirebaseSignUpRequestDto.java
  api/src/main/java/com/pickypal/api/auth/FirebaseSignUpResponseDto.java
  api/src/main/java/com/pickypal/api/auth/JwtKit.java
  api/src/main/java/com/pickypal/api/auth/LoginRequestDto.java
  api/src/main/java/com/pickypal/api/auth/LoginResponseDto.java
  api/src/main/java/com/pickypal/api/auth/SignUpRequestDto.java
  api/src/main/java/com/pickypal/api/user/ServiceUser.java
  api/src/main/java/com/pickypal/api/user/ServiceUserRepository.java
Labels: feat, backend

#34 납품업체 정보 관리에 대한 UI 구현
  Pickypal/src/main/java/branch/SupplierManageController.java
  Pickypal/src/main/resources/fxml/supplierManage.fxml
Labels: ui

#38 발주 관리 API 구현
  api/src/main/java/com/pickypal/api/order/Orders.java
  api/src/main/java/com/pickypal/api/order/OrdersController.java
  api/src/main/java/com/pickypal/api/order/OrdersRepository.java
  api/src/main/java/com/pickypal/api/order/OrdersSaveRequestDto.java
  api/src/main/java/com/pickypal/api/order/OrdersService.java
  api/src/main/java/com/pickypal/api/order/OrdersViewResponseDto.java
Labels: feat, backend

#41 재고 조회 API 구현
  api/src/main/java/com/pickypal/api/stock/BranchStockController.java
  api/src/main/java/com/pickypal/api/stock/BranchStockPageViewResponseDto.java
  api/src/main/java/com/pickypal/api/stock/BranchStockRepository.java
  api/src/main/java/com/pickypal/api/stock/BranchStockService.java
  api/src/main/java/com/pickypal/api/stock/BranchStockSingleViewResponseDto.java
  api/src/main/java/com/pickypal/api/stock/HeadStockController.java
  api/src/main/java/com/pickypal/api/stock/HeadStockPageViewResponseDto.java
  api/src/main/java/com/pickypal/api/stock/HeadStockRepository.java
  api/src/main/java/com/pickypal/api/stock/HeadStockService.java
  api/src/main/java/com/pickypal/api/stock/HeadStockSingleViewResponseDto.java
Labels: feat, backend

#42 본사로 회원가입 안되는 버그 패치
  api/src/main/java/com/pickypal/api/auth/AuthService.java
Labels: bug, backend

#45 클라이언트 TableView column에 맞추어 백엔드 dto 스펙 수정: 본사 재고 조회 dto
  api/src/main/java/com/pickypal/api/backdoor/BackdoorController.java
  api/src/main/java/com/pickypal/api/backdoor/BackdoorService.java
  api/src/main/java/com/pickypal/api/stock/BranchStockRepository.java
  api/src/main/java/com/pickypal/api/stock/HeadStockPageViewResponseDto.java
  api/src/main/java/com/pickypal/api/stock/HeadStockRepository.java
  api/src/main/java/com/pickypal/api/stock/HeadStockService.java
  api/src/main/java/com/pickypal/api/stock/HeadStockSingleViewResponseDto.java
Labels: refactor, backend

#46 전반적인 UI 수정 및 이벤트 연결
  Pickypal/build.gradle
  Pickypal/src/main/java/administrator/administratorModeController.java
  Pickypal/src/main/java/auth/LoginController.java
  Pickypal/src/main/java/branch/BranchMainLayoutController.java
  Pickypal/src/main/java/branch/BranchManageController.java
  Pickypal/src/main/java/branch/BranchOrdersController.java
  Pickypal/src/main/java/branch/BranchStockController.java
  Pickypal/src/main/java/branch/StockReadController.java
  Pickypal/src/main/java/branch/SupplierManageController.java
  Pickypal/src/main/java/common/BranchNavController.java
  Pickypal/src/main/java/common/HeadNavController.java
  Pickypal/src/main/java/common/HeaderController.java
  Pickypal/src/main/java/common/NavController.java
  Pickypal/src/main/java/head/HeadMainLayoutController.java
  Pickypal/src/main/java/head/HeadStockController.java
  Pickypal/src/main/java/login/LoginMain.java
  Pickypal/src/main/java/main/MainController.java
  Pickypal/src/main/java/main/PickypalMain.java
  Pickypal/src/main/resources/css/common.css
  Pickypal/src/main/resources/css/style.css
  Pickypal/src/main/resources/fxml/StockShortageView.fxml
  Pickypal/src/main/resources/fxml/administrator/AdministratorMode.fxml
  Pickypal/src/main/resources/fxml/auth/Login.fxml
  Pickypal/src/main/resources/fxml/auth/SignUp.fxml
  Pickypal/src/main/resources/fxml/branch/BranchIncomingManage.fxml
  Pickypal/src/main/resources/fxml/branch/BranchMainLayout.fxml
  Pickypal/src/main/resources/fxml/branch/BranchOrdersManage.fxml
  Pickypal/src/main/resources/fxml/branch/BranchOrdersRegist.fxml
  Pickypal/src/main/resources/fxml/branch/BranchStock.fxml
  Pickypal/src/main/resources/fxml/branchIncoming.fxml
  Pickypal/src/main/resources/fxml/branchManage.fxml
  Pickypal/src/main/resources/fxml/branchManage2.fxml
  Pickypal/src/main/resources/fxml/branchOrdersManage.fxml
  Pickypal/src/main/resources/fxml/common/BranchNav.fxml
  Pickypal/src/main/resources/fxml/common/HeadNav.fxml
  Pickypal/src/main/resources/fxml/common/Header.fxml
  Pickypal/src/main/resources/fxml/common/nav.fxml
  Pickypal/src/main/resources/fxml/head/BranchManage.fxml
  Pickypal/src/main/resources/fxml/head/HeadIncomingManage.fxml
  Pickypal/src/main/resources/fxml/head/HeadMainLayout.fxml
  Pickypal/src/main/resources/fxml/head/HeadOutgoingManage.fxml
  Pickypal/src/main/resources/fxml/head/HeadStock.fxml
  Pickypal/src/main/resources/fxml/head/SupplierManage.fxml
  Pickypal/src/main/resources/fxml/headOutgoingManage.fxml
  Pickypal/src/main/resources/fxml/headStock.fxml
  Pickypal/src/main/resources/fxml/incomingRegist.fxml
  Pickypal/src/main/resources/fxml/outgoingRegist.fxml
  Pickypal/src/main/resources/fxml/readStock.fxml
  Pickypal/src/main/resources/fxml/supplierManage.fxml
Labels: refactor, feat, ui

#51 본사의 발주내역 조회 api 구현
  api/src/main/java/com/pickypal/api/order/OrdersController.java
  api/src/main/java/com/pickypal/api/order/OrdersRepository.java
  api/src/main/java/com/pickypal/api/order/OrdersService.java
  api/src/main/java/com/pickypal/api/order/OrdersViewResponseDto.java
Labels: feat, backend

#53 출고 승인/거절 + 가상 출고완료 처리 api 구현
  api/src/main/java/com/pickypal/api/backdoor/BackdoorController.java
  api/src/main/java/com/pickypal/api/backdoor/BackdoorService.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItem.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemController.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemRepository.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemService.java
Labels: feat, backend

#55 본사 출고 내역 조회 api 구현
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemController.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemRepository.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemResponseDto.java
  api/src/main/java/com/pickypal/api/outgoing/HeadOutgoingItemService.java
Labels: feat, backend

#65 테이블 조회에 대한 API 호출 및 DTO 파싱 예제 코드 추가
  cli/build.gradle
  cli/src/main/java/com/pickypal/dto/stock/HeadStockViewResponseDto.java
  cli/src/main/java/com/pickypal/util/ApiKit.java
  cli/src/main/java/com/pickypal/util/ApiKitSample.java
Labels: bug, cli

#70 지점 입고조회 API 리팩토링
  api/src/main/java/com/pickypal/api/incoming/BranchIncomingItemController.java
  api/src/main/java/com/pickypal/api/incoming/BranchIncomingItemRepository.java
  api/src/main/java/com/pickypal/api/incoming/BranchIncomingItemService.java
Labels: refactor, backend

#72 지점 입고 조회 CLI 구현
  cli/src/main/java/com/pickypal/dto/incoming/BranchIncomingItemResponseDto.java
  cli/src/main/java/com/pickypal/screen/BranchIncomingScreen.java
Labels: cli

#74 API kit DELETE request 추가 및 auth POST 함수 수정
  cli/src/main/java/com/pickypal/util/ApiKit.java
Labels: feat, cli

#75 지점 발주 CRD 구현
  cli/src/main/java/com/pickypal/dto/order/OrdersSaveRequestDto.java
  cli/src/main/java/com/pickypal/dto/order/OrdersViewResponseDto.java
  cli/src/main/java/com/pickypal/screen/BranchOrderScreen.java
Labels: cli

#77 본사출고 CLI 및 API 연동 확인
  cli/src/main/java/com/pickypal/dto/outgoing/HeadOutgoingItemResponseDto.java
  cli/src/main/java/com/pickypal/screen/head/HeadOutgoingManageScreen.java
Labels: feat, cli
