Repository ssginc-be/Pickypal-WMS, pull requests merged in 2024-11, with the labels that each got.

#9 판매상품 크롤링 배치 및 API 서버 구축
  api/.gitattributes
  api/.gitignore
  api/build.gradle
  api/gradle/wrapper/gradle-wrapper.jar
  api/gradle/wrapper/gradle-wrapper.properties
  api/gradlew
  api/gradlew.bat
  api/settings.gradle
  api/src/main/java/com/pickypal/api/ApiApplication.java
  api/src/main/java/com/pickypal/api/domain/item/Emart24ItemCrawlController.java
  api/src/main/java/com/pickypal/api/domain/item/Emart24ItemCrawlService.java
  api/src/main/java/com/pickypal/api/domain/item/Item.java
  api/src/main/java/com/pickypal/api/domain/item/ItemRepository.java
  api/src/main/resources/application.yml
  api/src/test/java/com/pickypal/api/ApiApplicationTests.java
Labels: crawling, batch, backend

#10 본사 재고조회에 대한 UI 구현
  .gitignore
  Pickypal/build.gradle
  Pickypal/src/main/java/branch/BranchMain.java
  Pickypal/src/main/resources/fxml/headStock.fxml
Labels: ui

#11 지점 입고 조회에 대한 UI 구현
  Pickypal/src/main/java/branch/BranchIncomingController.java
  Pickypal/src/main/resources/fxml/branchIncoming.fxml
Labels: ui

#15 JavaFX 사이드바 화면 전환 적용
  Pickypal/build.gradle
  Pickypal/src/main/java/branch/BranchMain.java
  Pickypal/src/main/java/branch/BranchManageController.java
  Pickypal/src/main/java/login/LoginMain.java
  Pickypal/src/main/java/stock/StockReadController.java
  Pickypal/src/main/resources/css/style.css
  Pickypal/src/main/resources/fxml/branchManage.fxml
  Pickypal/src/main/resources/fxml/branchManage2.fxml
  Pickypal/src/main/resources/fxml/headStock.fxml
  Pickypal/src/main/resources/fxml/incomingRegist.fxml
  Pickypal/src/main/resources/fxml/outgoingRegist.fxml
  Pickypal/src/main/resources/fxml/readStock.fxml
  Pickypal/src/main/resources/fxml/supplierManage.fxml
Labels: ui

#17 `domain` 패키지 제거
  api/src/main/java/com/pickypal/api/item/Emart24ItemCrawlController.java
  api/src/main/java/com/pickypal/api/item/Emart24ItemCrawlService.java
  api/src/main/java/com/pickypal/api/item/Item.java
  api/src/main/java/com/pickypal/api/item/ItemRepository.java
Labels: backend
